### PR TITLE
ENH: Re-compressed all zip files to reduce file sizes

### PR DESCRIPTION
**Pull request by crazy25000**
### Problem:

Repo reached maximum allowed size in Github.

### Info:

Used 7zip, https://www.7-zip.org/, to re-compress all `.zip` files so that it helps reduce the size. Used simple loops to unzip all + re-compress back into zip files + delete CSV/TXT files:

```bash
# Unzip all files
for dir in ./2000-Jun2019/*/; do
 echo "$dir"
 cd "$dir" || exit
 unzip "*.zip"
 cd ../../
done

# Re-compress + delete old files
for dir in ./2000-Jun2019/*/; do
  cd "$dir" || exit
  for csv in *.csv; do
    echo "$csv"
    filename="${csv%.*}"
    7z a -r -mx=9 -tzip $filename "$filename*.csv" "$filename*.txt"
  done
  cd ../../
done
```

### Benchmarks:

Current Folder Size | New Folder Size
------------ | -------------
./2000-Jun2019 **2.5GB** | ./2000-Jun2019 **1.7GB**

### Possible Alternative: Gitlab

Gitlab offers 10GB https://about.gitlab.com/

### CODE REVIEW

**Comment by crazy25000** [comment]
@philipperemy would you also use the cleanup methods you mentioned in https://github.com/philipperemy/FX-1-Minute-Data/issues/9? I haven't used `git-filter-branch` or BFG before.

**Comment by philipperemy** [comment]
@crazy25000 thanks a lot. Yes I will use git filter branch beforehand!

**Comment by philipperemy** [comment]
@crazy25000 okay all the ZIP files in the master are gone now. I will merge this.

**Comment by philipperemy** [comment]
@crazy25000 I made it simpler. Instead of storing the files on Github, I'm now hosting them on Google Drive. It will allow a much easier update process.

You can can create a new PR with your script (as bash file): `recompress-zip.sh` at the root of the repo and I'll happily merge it.

Thanks for all :)


```bash
# Unzip all files
for dir in $1/*/; do
 echo "$dir"
 cd "$dir" || exit
 unzip "*.zip"
 cd ../../
done

# Re-compress + delete old files
for dir in ./$1/*/; do
  cd "$dir" || exit
  for csv in *.csv; do
    echo "$csv"
    filename="${csv%.*}"
    7z a -r -mx=9 -tzip $filename "$filename*.csv" "$filename*.txt"
  done
  cd ../../
done
```

**Comment by crazy25000** [comment]
You're welcome! Drive sounds good! I will open a new PR after changes are merged.

**Pull request closed without merging**
